Contract {
    setProvider: [Function],
    currentProvider: [Getter/Setter],
    _requestManager: RequestManager {
      provider: HttpProvider {
        withCredentials: false,
        timeout: 0,
        headers: undefined,
        agent: undefined,
        connected: false,
        host: 'https://bsc-dataseed1.defibit.io/',
        httpsAgent: [Agent]
      },
      providers: {
        WebsocketProvider: [Function: WebsocketProvider],
        HttpProvider: [Function: HttpProvider],
        IpcProvider: [Function: IpcProvider]
      },
      subscriptions: Map {}
    },
    givenProvider: null,
    providers: {
      WebsocketProvider: [Function: WebsocketProvider],
      HttpProvider: [Function: HttpProvider],
      IpcProvider: [Function: IpcProvider]
    },
    _provider: HttpProvider {
      withCredentials: false,
      timeout: 0,
      headers: undefined,
      agent: undefined,
      connected: false,
      host: 'https://bsc-dataseed1.defibit.io/',
      httpsAgent: Agent {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object]
      }
    },
    setRequestManager: [Function],
    BatchRequest: [Function: bound Batch],
    extend: [Function: ex] {
      formatters: {
        inputDefaultBlockNumberFormatter: [Function: inputDefaultBlockNumberFormatter],
        inputBlockNumberFormatter: [Function: inputBlockNumberFormatter],
        inputCallFormatter: [Function: inputCallFormatter],
        inputTransactionFormatter: [Function: inputTransactionFormatter],
        inputAddressFormatter: [Function: inputAddressFormatter],
        inputPostFormatter: [Function: inputPostFormatter],
        inputLogFormatter: [Function: inputLogFormatter],
        inputSignFormatter: [Function: inputSignFormatter],
        inputStorageKeysFormatter: [Function: inputStorageKeysFormatter],
        outputProofFormatter: [Function: outputProofFormatter],
        outputBigNumberFormatter: [Function: outputBigNumberFormatter],
        outputTransactionFormatter: [Function: outputTransactionFormatter],
        outputTransactionReceiptFormatter: [Function: outputTransactionReceiptFormatter],
        outputBlockFormatter: [Function: outputBlockFormatter],
        outputLogFormatter: [Function: outputLogFormatter],
        outputPostFormatter: [Function: outputPostFormatter],
        outputSyncingFormatter: [Function: outputSyncingFormatter]
      },
      utils: {
        _fireError: [Function: _fireError],
        _jsonInterfaceMethodToString: [Function: _jsonInterfaceMethodToString],
        _flattenTypes: [Function: _flattenTypes],
        randomHex: [Function: randomHex],
        _: [Function],
        BN: [Function],
        isBN: [Function: isBN],
        isBigNumber: [Function: isBigNumber],
        isHex: [Function: isHex],
        isHexStrict: [Function: isHexStrict],
        sha3: [Function],
        sha3Raw: [Function: sha3Raw],
        keccak256: [Function],
        soliditySha3: [Function: soliditySha3],
        soliditySha3Raw: [Function: soliditySha3Raw],
        encodePacked: [Function: encodePacked],
        isAddress: [Function: isAddress],
        checkAddressChecksum: [Function: checkAddressChecksum],
        toChecksumAddress: [Function: toChecksumAddress],
        toHex: [Function: toHex],
        toBN: [Function: toBN],
        bytesToHex: [Function: bytesToHex],
        hexToBytes: [Function: hexToBytes],
        hexToNumberString: [Function: hexToNumberString],
        hexToNumber: [Function: hexToNumber],
        toDecimal: [Function: hexToNumber],
        numberToHex: [Function: numberToHex],
        fromDecimal: [Function: numberToHex],
        hexToUtf8: [Function: hexToUtf8],
        hexToString: [Function: hexToUtf8],
        toUtf8: [Function: hexToUtf8],
        stripHexPrefix: [Function: stripHexPrefix],
        utf8ToHex: [Function: utf8ToHex],
        stringToHex: [Function: utf8ToHex],
        fromUtf8: [Function: utf8ToHex],
        hexToAscii: [Function: hexToAscii],
        toAscii: [Function: hexToAscii],
        asciiToHex: [Function: asciiToHex],
        fromAscii: [Function: asciiToHex],
        unitMap: [Object],
        toWei: [Function: toWei],
        fromWei: [Function: fromWei],
        padLeft: [Function: leftPad],
        leftPad: [Function: leftPad],
        padRight: [Function: rightPad],
        rightPad: [Function: rightPad],
        toTwosComplement: [Function: toTwosComplement],
        isBloom: [Function: isBloom],
        isUserEthereumAddressInBloom: [Function: isUserEthereumAddressInBloom],
        isContractAddressInBloom: [Function: isContractAddressInBloom],
        isTopic: [Function: isTopic],
        isTopicInBloom: [Function: isTopicInBloom],
        isInBloom: [Function: isInBloom],
        compareBlockNumbers: [Function: compareBlockNumbers]
      },
      Method: [Function: Method]
    },
    clearSubscriptions: [Function],
    options: { address: [Getter/Setter], jsonInterface: [Getter/Setter] },
    handleRevert: [Getter/Setter],
    defaultCommon: [Getter/Setter],
    defaultHardfork: [Getter/Setter],
    defaultChain: [Getter/Setter],
    transactionPollingTimeout: [Getter/Setter],
    transactionConfirmationBlocks: [Getter/Setter],
    transactionBlockTimeout: [Getter/Setter],
    defaultAccount: [Getter/Setter],
    defaultBlock: [Getter/Setter],
    methods: {
      BONUS_MULTIPLIER: [Function: bound _createTxObject],
      '0x8aa28550': [Function: bound _createTxObject],
      'BONUS_MULTIPLIER()': [Function: bound _createTxObject],
      add: [Function: bound _createTxObject],
      '0x1eaaa045': [Function: bound _createTxObject],
      'add(uint256,address,bool)': [Function: bound _createTxObject],
      cake: [Function: bound _createTxObject],
      '0xdce17484': [Function: bound _createTxObject],
      'cake()': [Function: bound _createTxObject],
      cakePerBlock: [Function: bound _createTxObject],
      '0x0755e0b6': [Function: bound _createTxObject],
      'cakePerBlock()': [Function: bound _createTxObject],
      deposit: [Function: bound _createTxObject],
      '0xe2bbb158': [Function: bound _createTxObject],
      'deposit(uint256,uint256)': [Function: bound _createTxObject],
      dev: [Function: bound _createTxObject],
      '0x8d88a90e': [Function: bound _createTxObject],
      'dev(address)': [Function: bound _createTxObject],
      devaddr: [Function: bound _createTxObject],
      '0xd49e77cd': [Function: bound _createTxObject],
      'devaddr()': [Function: bound _createTxObject],
      emergencyWithdraw: [Function: bound _createTxObject],
      '0x5312ea8e': [Function: bound _createTxObject],
      'emergencyWithdraw(uint256)': [Function: bound _createTxObject],
      enterStaking: [Function: bound _createTxObject],
      '0x41441d3b': [Function: bound _createTxObject],
      'enterStaking(uint256)': [Function: bound _createTxObject],
      getMultiplier: [Function: bound _createTxObject],
      '0x8dbb1e3a': [Function: bound _createTxObject],
      'getMultiplier(uint256,uint256)': [Function: bound _createTxObject],
      leaveStaking: [Function: bound _createTxObject],
      '0x1058d281': [Function: bound _createTxObject],
      'leaveStaking(uint256)': [Function: bound _createTxObject],
      massUpdatePools: [Function: bound _createTxObject],
      '0x630b5ba1': [Function: bound _createTxObject],
      'massUpdatePools()': [Function: bound _createTxObject],
      migrate: [Function: bound _createTxObject],
      '0x454b0608': [Function: bound _createTxObject],
      'migrate(uint256)': [Function: bound _createTxObject],
      migrator: [Function: bound _createTxObject],
      '0x7cd07e47': [Function: bound _createTxObject],
      'migrator()': [Function: bound _createTxObject],
      owner: [Function: bound _createTxObject],
      '0x8da5cb5b': [Function: bound _createTxObject],
      'owner()': [Function: bound _createTxObject],
      pendingCake: [Function: bound _createTxObject],
      '0x1175a1dd': [Function: bound _createTxObject],
      'pendingCake(uint256,address)': [Function: bound _createTxObject],
      poolInfo: [Function: bound _createTxObject],
      '0x1526fe27': [Function: bound _createTxObject],
      'poolInfo(uint256)': [Function: bound _createTxObject],
      poolLength: [Function: bound _createTxObject],
      '0x081e3eda': [Function: bound _createTxObject],
      'poolLength()': [Function: bound _createTxObject],
      renounceOwnership: [Function: bound _createTxObject],
      '0x715018a6': [Function: bound _createTxObject],
      'renounceOwnership()': [Function: bound _createTxObject],
      set: [Function: bound _createTxObject],
      '0x64482f79': [Function: bound _createTxObject],
      'set(uint256,uint256,bool)': [Function: bound _createTxObject],
      setMigrator: [Function: bound _createTxObject],
      '0x23cf3118': [Function: bound _createTxObject],
      'setMigrator(address)': [Function: bound _createTxObject],
      startBlock: [Function: bound _createTxObject],
      '0x48cd4cb1': [Function: bound _createTxObject],
      'startBlock()': [Function: bound _createTxObject],
      syrup: [Function: bound _createTxObject],
      '0x86a952c4': [Function: bound _createTxObject],
      'syrup()': [Function: bound _createTxObject],
      totalAllocPoint: [Function: bound _createTxObject],
      '0x17caf6f1': [Function: bound _createTxObject],
      'totalAllocPoint()': [Function: bound _createTxObject],
      transferOwnership: [Function: bound _createTxObject],
      '0xf2fde38b': [Function: bound _createTxObject],
      'transferOwnership(address)': [Function: bound _createTxObject],
      updateMultiplier: [Function: bound _createTxObject],
      '0x5ffe6146': [Function: bound _createTxObject],
      'updateMultiplier(uint256)': [Function: bound _createTxObject],
      updatePool: [Function: bound _createTxObject],
      '0x51eb05a6': [Function: bound _createTxObject],
      'updatePool(uint256)': [Function: bound _createTxObject],
      userInfo: [Function: bound _createTxObject],
      '0x93f1a40b': [Function: bound _createTxObject],
      'userInfo(uint256,address)': [Function: bound _createTxObject],
      withdraw: [Function: bound _createTxObject],
      '0x441a3e70': [Function: bound _createTxObject],
      'withdraw(uint256,uint256)': [Function: bound _createTxObject]
    },
    events: {
      Deposit: [Function: bound ],
      '0x90890809c654f11d6e72a28fa60149770a0d11ec6c92319d6ceb2bb0a4ea1a15': [Function: bound ],
      'Deposit(address,uint256,uint256)': [Function: bound ],
      EmergencyWithdraw: [Function: bound ],
      '0xbb757047c2b5f3974fe26b7c10f732e7bce710b0952a71082702781e62ae0595': [Function: bound ],
      'EmergencyWithdraw(address,uint256,uint256)': [Function: bound ],
      OwnershipTransferred: [Function: bound ],
      '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0': [Function: bound ],
      'OwnershipTransferred(address,address)': [Function: bound ],
      Withdraw: [Function: bound ],
      '0xf279e6a1f5e320cca91135676d9cb6e44ca8a08c0b88342bcdb1144f6511b568': [Function: bound ],
      'Withdraw(address,uint256,uint256)': [Function: bound ],
      allEvents: [Function: bound ]
    },
    _address: '0x73feaa1eE314F8c655E354234017bE2193C9E24E',
    _jsonInterface: [
      {
        inputs: [Array],
        stateMutability: 'nonpayable',
        type: 'constructor',
        constant: undefined,
        payable: undefined
      },
      {
        anonymous: false,
        inputs: [Array],
        name: 'Deposit',
        type: 'event',
        constant: undefined,
        payable: undefined,
        signature: '0x90890809c654f11d6e72a28fa60149770a0d11ec6c92319d6ceb2bb0a4ea1a15'
      },
      {
        anonymous: false,
        inputs: [Array],
        name: 'EmergencyWithdraw',
        type: 'event',
        constant: undefined,
        payable: undefined,
        signature: '0xbb757047c2b5f3974fe26b7c10f732e7bce710b0952a71082702781e62ae0595'
      },
      {
        anonymous: false,
        inputs: [Array],
        name: 'OwnershipTransferred',
        type: 'event',
        constant: undefined,
        payable: undefined,
        signature: '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0'
      },
      {
        anonymous: false,
        inputs: [Array],
        name: 'Withdraw',
        type: 'event',
        constant: undefined,
        payable: undefined,
        signature: '0xf279e6a1f5e320cca91135676d9cb6e44ca8a08c0b88342bcdb1144f6511b568'
      },
      {
        inputs: [],
        name: 'BONUS_MULTIPLIER',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x8aa28550'
      },
      {
        inputs: [Array],
        name: 'add',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x1eaaa045'
      },
      {
        inputs: [],
        name: 'cake',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0xdce17484'
      },
      {
        inputs: [],
        name: 'cakePerBlock',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x0755e0b6'
      },
      {
        inputs: [Array],
        name: 'deposit',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0xe2bbb158'
      },
      {
        inputs: [Array],
        name: 'dev',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x8d88a90e'
      },
      {
        inputs: [],
        name: 'devaddr',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0xd49e77cd'
      },
      {
        inputs: [Array],
        name: 'emergencyWithdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x5312ea8e'
      },
      {
        inputs: [Array],
        name: 'enterStaking',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x41441d3b'
      },
      {
        inputs: [Array],
        name: 'getMultiplier',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x8dbb1e3a'
      },
      {
        inputs: [Array],
        name: 'leaveStaking',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x1058d281'
      },
      {
        inputs: [],
        name: 'massUpdatePools',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x630b5ba1'
      },
      {
        inputs: [Array],
        name: 'migrate',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x454b0608'
      },
      {
        inputs: [],
        name: 'migrator',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x7cd07e47'
      },
      {
        inputs: [],
        name: 'owner',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x8da5cb5b'
      },
      {
        inputs: [Array],
        name: 'pendingCake',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x1175a1dd'
      },
      {
        inputs: [Array],
        name: 'poolInfo',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x1526fe27'
      },
      {
        inputs: [],
        name: 'poolLength',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x081e3eda'
      },
      {
        inputs: [],
        name: 'renounceOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x715018a6'
      },
      {
        inputs: [Array],
        name: 'set',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x64482f79'
      },
      {
        inputs: [Array],
        name: 'setMigrator',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x23cf3118'
      },
      {
        inputs: [],
        name: 'startBlock',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x48cd4cb1'
      },
      {
        inputs: [],
        name: 'syrup',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x86a952c4'
      },
      {
        inputs: [],
        name: 'totalAllocPoint',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x17caf6f1'
      },
      {
        inputs: [Array],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0xf2fde38b'
      },
      {
        inputs: [Array],
        name: 'updateMultiplier',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x5ffe6146'
      },
      {
        inputs: [Array],
        name: 'updatePool',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x51eb05a6'
      },
      {
        inputs: [Array],
        name: 'userInfo',
        outputs: [Array],
        stateMutability: 'view',
        type: 'function',
        constant: true,
        payable: undefined,
        signature: '0x93f1a40b'
      },
      {
        inputs: [Array],
        name: 'withdraw',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
        constant: undefined,
        payable: undefined,
        signature: '0x441a3e70'
      }
    ]
  }